### ISSUE TITLE
Consider removing the 5 seconds wait before redirecting

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote-docker#15]
There is a 5 second wait on the main page with a loading wheel before redirecting to the novnc page.  This waits may not be needed any more for simphony-remote >= 0.2.0

**Comment by stefanoborini** [comment]
Just as a note.

The wait is there for the following reason: we poll until the container webserver replies with a valid code, then redirect. The problem is that when this happens, it means that the webserver is operative and there's something listening, but that does not guarantee that the X11 system and everything else is operative. In fact, it is not, and therefore the wait was added.

I don't think it's a good idea to remove it for two reasons:

1. It's not trivial. We would have to let the central manager know that "everything is clear" through other means instead of the webserver. Some support code in the container that gives the thumbs up is one option, but it complicates things.
2. We still need to wait. The system is not operative, and waiting would mean staying in the app manager longer. This would be, imho, perceived sluggishness. Redirecting to the spinner at least shows the user something is happening.

The main problem is with the View (we get the spinner all the time, even when the system is already up and running, but that is solved in the new interface anyway.
